# Imagem: https://www.docker.elastic.co/


ARG ELK_VERSION

FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

# Adicionar plugins do Logstash aqui.  Insertar via dockerfile 
# para manter unitário o arquivo de configuração do serviço.
